### ISSUE TITLE
Mish-cuda installation failed.

### ISSUE THREAD

**Issue by yedmed** [thomasbrandon/mish-cuda#4]
Hi, i am trying to install mish-cuda using `"pip install git+https://github.com/thomasbrandon/mish-cuda/`
However i am getting _ERROR: Failed building wheel for mish-cuda_. 
I am using cuda 10.1 with pytorch 1.5. Any suggestion? Thanks

**Comment by thomasbrandon** [comment]
Without a specific error message it's hard to know. Make sure the CUDA SDK is installed and accessible through the `CUDA_HOME` environment variable.
Otherwise you'd need to get a better error. You could try running pip verbosely (`pip -v ...`) and see if that gives full messages. Otherwise clone the repo and try directly running `python setup.py -v install` (or maybe you might need to specifically run python `setup.py -v build` or `python setup.py -v build_ext`).-

**Comment by CzKerwin** [comment]
I get same problem using cuda 11.0 with pytorch 1.7. I try running `python setup.py -v build`.
 

> FAILED: /app/share/mish-cuda/build/temp.linux-x86_64-3.8/csrc/mish_kernel.o /usr/local/cuda/bin/nvcc -Iexternal -I/opt/conda/lib/python3.8/site-packages/torch/include -I/opt/conda/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/opt/conda/lib/python3.8/site-packages/torch/include/TH -I/opt/conda/lib/python3.8/site-packages/torch/include/THC -I/usr/local/cuda/include -I/opt/conda/include/python3.8 -c -c /app/share/mish-cuda/csrc/mish_kernel.cu -o /app/share/mish-cuda/build/temp.linux-x86_64-3.8/csrc/mish_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' --expt-extended-lambda -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'

**Comment by thomasbrandon** [comment]
CUDA 11.0 doesn't support RTX30 series cards. They were introduced in CUDA 11.1.

**Comment by CzKerwin** [comment]
> CUDA 11.0 doesn't support RTX30 series cards. They were introduced in CUDA 11.1.

Thank you very much for clearing my doubt.

**Comment by JobCollins** [comment]
> Without a specific error message it's hard to know. Make sure the CUDA SDK is installed and accessible through the `CUDA_HOME` environment variable.
> Otherwise you'd need to get a better error. You could try running pip verbosely (`pip -v ...`) and see if that gives full messages. Otherwise clone the repo and try directly running `python setup.py -v install` (or maybe you might need to specifically run python `setup.py -v build` or `python setup.py -v build_ext`).-

Hey @thomasbrandon I have tried following this but I get the following error back

`Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    'build_ext': BuildExtension
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/usr/local/lib/python3.7/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/local/lib/python3.7/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 456, in unix_wrap_single_compile
    cflags = unix_cuda_flags(cflags)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 423, in unix_cuda_flags
    cflags + _get_cuda_arch_flags(cflags))
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/cpp_extension.py", line 1561, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range`
